services:
  - type: web
    name: freeauditoriummitso
    env: node
    buildCommand: npm run build
    startCommand: npm run preview
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /api/*
        destination: https://apps.mitso.by/frontend/web/*